### ISSUE TITLE
Misc tweaks to nsimpl.cpp

### ISSUE THREAD

**Issue by dpage** [jonmmorgan/wxwebconnect#3]
Not sure if you're interested in these changes - they're from the project I'm working on which includes other tweaks to the code, but these seemed like they might be useful more generally. The may not apply entirely cleanly, but should be easy to manually apply:

```
- Remove an unused function
- Fix a typo
- Use wxWidgets error handling, and avoid a potential crash on *nix 
  (cannot pass non-POD type...)
- Look for system versions of the XULRunner libraries, if they're
  not found in the XULRunner directory, which is the case on some
  Linux distros which won't duplicate libraries in /usr/lib.
```

<pre>
diff --git a/webconnect/nsimpl.cpp b/webconnect/nsimpl.cpp
index 76466bc..0c8fa81 100644
--- a/webconnect/nsimpl.cpp
+++ b/webconnect/nsimpl.cpp
@@ -98,11 +98,6 @@ struct XPCOMFunctionTable
 
 static XPCOMFunctionTable funcs;
 
-static bool isLibraryOk()
-{
-    return (funcs.Init != 0) ? true : false;
-}
-
 typedef nsresult (PR_CALLBACK *GetFrozenFunctionsFunc)(XPCOMFunctionTable *func_table,
                                                        const char* path);
 
@@ -224,7 +219,11 @@ nsresult XPCOMGlueStartup(const char* xpcom_dll_path)
         void* handle = dlopen(deplibs.Item(i).mbc_str(), RTLD_GLOBAL | RTLD_LAZY);
         if (!handle)
         {
-            fprintf(stderr, "dlopen %s failed! Error was:\n%s\n", deplibs.Item(i).mbc_str(), dlerror());
+            void* handle = dlopen(deplibs.Item(i).AfterLast('/').mbc_str(), RTLD_GLOBAL | RTLD_LAZY);
+            if (!handle)
+            {
+                wxLogError(_("dlopen %s failed! Error:\n%s"), deplibs.Item(i).c_str(), wxString::FromAscii(dlerror()).c_str());
+            }
         }
     }
     
@@ -233,11 +232,11 @@ nsresult XPCOMGlueStartup(const char* xpcom_dll_path)
     void* h = dlopen(xpcom_dll_path, RTLD_GLOBAL | RTLD_LAZY);
     if (!h)
     {
-        fprintf(stderr, "dlopen %s failed! Error was:\n%s\n", xpcom_dll_path, dlerror());
+        wxLogError(_("dlopen %s failed! Error:\n%s"), xpcom_dll_path, wxString::FromAscii(dlerror()).c_str());
         return NS_ERROR_FAILURE;
     }
         
-    GetFrozenFunctionsFunc f =
+    GetFrozenFunctionsFunc f;
     f = (GetFrozenFunctionsFunc)dlsym(h, "NS_GetFrozenFunctions");
     if (!f)
     {

</pre>

**Comment by jonmmorgan** [comment]
I have made these changes in some form.  I wish I had paid attention to the wxLogError changes earlier, as it would have saved me a day tracking down why loading the library was failing on Linux ;).  Thanks!
