### ISSUE TITLE
Application menu gets invisible and not able to select combo box item 

### ISSUE THREAD

**Issue by akshay-joshi** [jonmmorgan/wxwebconnect#7]
Hi 

I am building one application using wxWidget-2.9.3 on Mac OSX. I am using wxwebconnect library. Before calling Gecko::init() function everything works fine.  When Gecko::init() function gets called I am not able to see my applications menu and also not able to select any item from wxComboBox. When I clicked on combo box the drop down menu disappears very quickly, before I will select any item.  

I have seen the above mentioned behavior only on Mac OSX. On Windows and Linux everything works fine.

Then I analyze Gecko::init() function and found that  call "comp_mgr->CreateInstanceByContractID(contract_id, 0, nsISupportsIID,(void **)&res.p);"  inside function "ns_smartptr<nsISupports> nsCreateInstance(const char *contract_id)"  of nsimpl.cpp actually creates both the above mentioned problem. 

As per my understanding this call stealing the focus, so that application menu gets invisible.

Is there any solution to this problem, please help me.

**Comment by akshay-joshi** [comment]
Can someone help me on the above issue.

**Comment by jonmmorgan** [comment]
Sorry I haven't replied, but I have never used wxWebConnect on Mac OS X and in fact don't even have a Mac.  You might like to try the Kirix Forums (http://www.kirix.com/forums/), as Kirix originally developed most of wxWebConnect, including the Mac support.
